require('mini.ai').setup()
require('mini.comment').setup()
require('mini.cursorword').setup()
require('mini.indentscope').setup()
require('mini.move').setup()
require('mini.pairs').setup()
require('mini.surround').setup()
