syntax enable
set number
set relativenumber
set cursorline
set mouse=nv
set numberwidth=1
set showcmd
set ruler
set encoding=utf-8
set showmatch
set smarttab
set expandtab
set softtabstop=2
set shiftwidth=2
set laststatus=2
set signcolumn=yes
set clipboard+=unnamedplus
set nobackup
set nowrap
set noswapfile
set smartindent
set splitbelow
set splitright
set termguicolors
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
set tabstop=2
set nofoldenable 
